insert into Question values 
('Q001','Combien de temps faut-il pour que le CO2 soit éliminé de l''atmosphère?', 'C1'),
('Q002','Comment appelle-t-on la couche de gaz qui entoure la Terre?', 'C1'),
('Q003','Quelle est la couche de l''atmosphère qui contient la plupart des gaz de l''air ', 'C1'),
('Q004','Quel est le gaz le plus abondant dans l''atmosphère terrestre ?', 'C1'),
('Q005','Quel est le nom du phénomène qui se produit lorsqu''une masse d''air chaud rencontre une masse d''air froid ?', 'C1'),
('Q006','À quelle altitude l''air devient-il techniquement considéré comme "air rare" ?', 'C1'),
('Q007','De quelle couleur est le ciel à haute altitude ?', 'C1'),
('Q008','Combien de temps peut-on survivre sans air ?', 'C1'),
('Q009','Dans quelle ville a été réalisé le premier vol en ballon captif en 1783 ?', 'C1'),
('Q010','Quel est le principal gaz à effet de serre produit par les activités humaines ?', 'C1'),
('Q011','À quelle vitesse peut voyager un avion de ligne à haute altitude ?', 'C1'),
('Q012','Quel est le nom de l''instrument utilisé pour mesurer la pression atmosphérique ?', 'C1'),
('Q013','Quel est le nom de la zone atmosphérique où se produit la plupart des phénomènes météorologiques ?', 'C1'),
('Q014','Quel est le nom de l''instrument utilisé pour mesurer la vitesse du vent ?', 'C1'),
('Q015','Quelle est la vitesse de la lumière dans l''air ?', 'C1'),
('Q016','Quelle est la température à laquelle l''eau gèle ?', 'C1'),
('Q017','À quelle altitude se trouve la couche d''ozone dans l''atmosphère ?', 'C1'),
('Q018','Quel est le nom de l''instrument utilisé pour mesurer l''humidité de l''air ?', 'C1'),
('Q019','Quel est le nom de la zone atmosphérique où se trouvent les aurores boréales et australes ?', 'C1'),
('Q020','À quelle altitude se trouve la station spatiale internationale (ISS) ?', 'C1'),
('Q021','Quel est le nom du processus par lequel l''air chaud monte et l''air froid descend ?', 'C1'),
('Q022','Quel est le nom du phénomène atmosphérique qui se produit lorsqu''un front froid rencontre un front chaud ?', 'C1'),
('Q023','Quel est le nom de l''instrument utilisé pour mesurer la qualité de l''air ?', 'C1'),
('Q024','Quelle est la pression atmosphérique moyenne au niveau de la mer ?', 'C1'),
('Q025','Quel est le nom du processus par lequel les nuages se forment à partir de la vapeur d''eau dans l''air ?', 'C1'),

('Q026','Quelle est la température moyenne annuelle en France mesurée en 2020?', 'C2'),
('Q027','Quelle est la principale cause de l''augmentation du niveau de la mer ?', 'C2'),
('Q028','Qu''est-ce qui peut causer le changement climatique ?', 'C2'),
('Q029','Quelle est la différence entre le climat et la météo ?', 'C2'),
('Q030','Quel est l''effet des tempêtes tropicales sur le climat ?', 'C2'),
('Q031','Qu''est-ce que l''acidification des océans ?', 'C2'),
('Q032','Quel est le principal facteur qui influence le climat dans une région donnée ?', 'C2'),
('Q033','Quelle est l''importance des courants océaniques dans la régulation du climat ?', 'C2'),
('Q034','Qu''est-ce que la couche d''ozone ?', 'C2'),
('Q035','Quel est l''impact du changement climatique sur la biodiversité ?', 'C2'),
('Q036','Qu''est-ce que l''effet albedo ?', 'C2'),
('Q037','Quel est l''impact du réchauffement climatique sur les régions polaires ?', 'C2'),
('Q038','Qu''est-ce que la désertification ?', 'C2'),
('Q039','Qu''est-ce que l''effet El Niño ?', 'C2'),
('Q040','Qu''est-ce que la biomasse ?', 'C2'),
('Q041','Quel est le plus grand émetteur de gaz à effet de serre dans le monde?', 'C2'),
('Q042','À quelle distance se trouve la Terre du soleil?', 'C2'),
('Q043','Quelle est la principale source d''énergie renouvelable dans le monde?', 'C2'),
('Q044','Qu''est-ce que l''indice de chaleur?', 'C2'),
('Q045','Quel est le plus grand glacier au monde?', 'C2'),
('Q046','Quelle est la plus grande source de gaz à effet de serre dans l''agriculture?', 'C2'),
('Q047','Quelle est la température la plus élevée jamais enregistrée sur Terre?', 'C2'),
('Q048','Quel est le plus grand désert chaud du monde?', 'C2'),
('Q049','Qu''est-ce que le Gulf Stream ?', 'C2'),
('Q050','Qu''est-ce que la séquestration du carbone?', 'C2'),

('Q051','Combien de temps faut-il pour qu''une bouteille en plastique se décompose dans la nature?', 'C3'),
('Q052','Quelle est la durée de vie moyenne d''une bouteille en plastique dans un dépotoir ?', 'C3'),
('Q053','Combien de temps faut-il pour qu''un chewing-gum se décompose dans la nature ?', 'C3'),
('Q054','Quel est le pourcentage de déchets plastiques qui ont été recyclés depuis que le recyclage a été introduit ?', 'C3'),
('Q055','Quel est le principal matériau utilisé pour fabriquer des sacs en plastique ?', 'C3'),
('Q056','Combien de tonnes de déchets électroniques sont générées chaque année dans le monde ?', 'C3'),
('Q057','Quel est le gaz à effet de serre le plus émis par les décharges ?', 'C3'),
('Q058','Quel est le principal type de déchet produit par les ménages aux États-Unis ?', 'C3'),
('Q059','Combien de bouteilles en plastique sont vendues chaque minute dans le monde ?', 'C3'),
('Q060','Quelle est la quantité de papier que les États-Unis jettent chaque année ?', 'C3'),
('Q061','Combien de temps faut-il pour qu''une canette en aluminium se décompose dans la nature ?', 'C3'),
('Q062','Quelle est la quantité de déchets électroniques produite par personne chaque année dans le monde ?', 'C3'),
('Q063','Quelle est la ville la plus peuplée des États-Unis à interdire les pailles en plastique ?', 'C3'),
('Q064','Quel est le pourcentage de déchets plastiques qui finissent dans l''océan ?', 'C3'),
('Q065','Combien de temps faut-il pour qu''un mégot de cigarette se décompose dans la nature ?', 'C3'),
('Q066','Quel est le pourcentage de déchets alimentaires gaspillés chaque année dans le monde ?', 'C3'),
('Q067','Quel est le principal produit plastique jetable utilisé dans le monde ?', 'C3'),
('Q068','Combien de temps faut-il pour qu''une bouteille en verre se décompose dans la nature ?', 'C3'),
('Q069','Quel est le principal type de déchet généré par l''industrie de la construction ?', 'C3'),
('Q070','Quel est le pourcentage de papier recyclé dans le monde en 2021 ?', 'C3'),
('Q071','Quelle est la ville la plus verte des États-Unis en termes de gestion des déchets ?', 'C3'),
('Q072','Combien de tonnes de déchets alimentaires sont produits chaque année dans le monde ?', 'C3'),
('Q073','Quel est le principal matériau utilisé pour fabriquer des bouteilles en verre ?', 'C3'),
('Q074','Quelle est la ville la plus peuplée d''Europe à interdire les voitures diesel ?', 'C3'),
('Q075','Quel est le pourcentage de déchets électroniques exportés vers les pays en développement chaque année ?', 'C3'),

('Q076','La biodiversité peut être définie de manière suivante:', 'C4'),
('Q077','Quel animal parmi les suivants ne fait pas partie des animaux protégés en France?', 'C4'),
('Q078','Dans le cas des plantes vertes, la photosynthèse est effectuée:', 'C4'),
('Q079','Dans le cas des plantes vertes, le processus de photosynthèse:', 'C4'),
('Q080','Qu''est-ce qu''une cellule?', 'C4'),
('Q081','Qu''est-ce qu''un organe?', 'C4'),
('Q082','Quelle est la fonction de l''ADN?', 'C4'),
('Q083','Comment est formé un organisme multicellulaire?', 'C4'),
('Q084','Quel est le rôle des mitochondries dans une cellule?', 'C4'),
('Q085','Qu''est-ce que la respiration cellulaire?', 'C4'),
('Q086','Qu''est-ce que la reproduction sexuée?', 'C4'),
('Q087','Qu''est-ce que la méiose?', 'C4'),
('Q088','Qu''est-ce que l''évolution?', 'C4'),
('Q089','Qu''est-ce qu''un reptile?', 'C4'),
('Q090','Quel organe du corps humain produit l''insuline', 'C4'),
('Q091','Quel est le plus petit os du corps humain ?', 'C4'),
('Q092','Dans quelle partie de la plante se produit la photosynthèse ?', 'C4'),
('Q093','Quel organe est responsable de la filtration du sang ?', 'C4'),
('Q094','Dans quelle partie de l''œil se trouve la rétine ?', 'C4'),
('Q095','Quel est le rôle principal des globules rouges ?', 'C4'),
('Q096','Quel organe est responsable de la production de la bile ?', 'C4'),
('Q097','Quel est le nom de l''enzyme qui digère les protéines dans l''estomac ?', 'C4'),
('Q098','Quel est le nom de la maladie causée par une carence en vitamine C ?', 'C4'),
('Q099','Quel est le nom de la molécule qui stocke l''énergie dans les cellules ?', 'C4'),
('Q100','Quel est le nom du processus par lequel les plantes produisent de l''énergie en l''absence de lumière ?', 'C4'),

('Q101','Quelle est la principale source de pollution plastique dans les océans?', 'C5'),
('Q102','Quel est le type de plastique qui met le plus de temps à se décomposer?', 'C5'),
('Q103','Quelle est la principale utilisation du plastique qui contribue à sa pollution?', 'C5'),
('Q104','Quelle est la proportion de plastique qui est récupérée et recyclée dans le monde?', 'C5'),
('Q105','Quel est l''effet le plus néfaste de la pollution plastique sur les océans?', 'C5'),
('Q106','Quel est le principal moyen de réduire la pollution plastique?', 'C5'),
('Q107','Quelle est la principale source de pollution de l''air en ville?', 'C5'),
('Q108','Quelle est la principale source de pollution sonore?', 'C5'),
('Q109','Quelle est la principale source de pollution lumineuse?', 'C5'),
('Q110','Quelle est la principale source de pollution des sols?', 'C5'),
('Q111','Quel est le principal moyen de transport responsable de la pollution de l''air en ville?', 'C5'),
('Q112','Quel est le principal gaz à effet de serre émis par les moyens de transport?', 'C5'),
('Q113','Quel est le principal moyen de transport écologique?', 'C5'),
('Q114','Quel est le principal moyen de transport qui contribue à la pollution sonore?', 'C5'),
('Q115','Quelle est la principale source de pollution des moyens de transport terrestres?', 'C5'),
('Q116','Quel est le meilleur remplacement pour les sacs en plastique à usage unique?', 'C5'),
('Q117','Quel est le meilleur remplacement pour les gobelets en plastique à usage unique?', 'C5'),
('Q118','Quel est le meilleur remplacement pour les bouteilles en plastique à usage unique?', 'C5'),
('Q119','Quelle est la principale mesure prise par le gouvernement pour réduire la pollution de l''air?', 'C5'),
('Q120','Quelle est la principale mesure prise par le gouvernement pour réduire la pollution des villes?', 'C5'),
('Q121','Quel est le principal impact de la pollution lumineuse sur l''environnement?', 'C5'),
('Q122','Quelle est la principale cause de la pollution sonore?', 'C5'),
('Q123','Quels sont les effets négatifs de la pollution sonore sur la santé humaine?', 'C5'),
('Q124','Quelle est la principale cause de la pollution des sols?', 'C5'),
('Q125','Quels sont les effets négatifs de la pollution des sols sur l''environnement?', 'C5'),

('Q126','Quelle est la principale source de pollution de l''eau?', 'C6'),
('Q127','Quelle est la principale source de pollution des océans?', 'C6'),
('Q128','Quelle est la principale source d''eau potable pour les humains?', 'C6'),
('Q129','Quels sont les principaux polluants de l''eau?', 'C6'),
('Q130','Quelle est la quantité d''eau douce disponible sur terre?', 'C6'),
('Q131','Quelle est la principale utilisation de l''eau douce sur terre?', 'C6'),
('Q132','Quel est l''impact de la surexploitation des ressources en eau sur les écosystèmes?', 'C6'),
('Q133','Quelle est la formule chimique de l''eau?', 'C6'),
('Q134','De quoi est constitué un iceberg?', 'C6'),
('Q135','Quel est le pourcentage d''eau sur Terre?', 'C6'),
('Q136','Est-ce que l''eau du robinet peut être utilisée pour boire et cuisiner?', 'C6'),
('Q137','L’eau est le principal constituant du corps humain, en quelle quantité est-il présent?', 'C6'),
('Q138','Combien de jours une personne peut rester sans boire de l’eau?', 'C6'),
('Q139','Combien de litres d''eau utilise une personne en moyenne par jour pour ses besoins quotidiens ?', 'C6'),
('Q140','Quel est le plus grand contributeur mondial à la pollution des eaux ?', 'C6'),
('Q141','Quel est le facteur le plus important à prendre en compte pour évaluer la qualité de l''eau ?', 'C6'),
('Q142','Combien de pourcentage de la Terre est couvert d''eau ?', 'C6'),
('Q143','Où se trouvent la plupart des icebergs ?', 'C6'),
('Q144','Quel est l''impact le plus courant de la pollution des eaux sur la faune aquatique ?', 'C6'),
('Q145','Quel est le principal usage de l''eau dans les foyers ?', 'C6'),
('Q146','Quel est le principal facteur qui détermine la consommation d''eau dans les foyers ?', 'C6'),
('Q147','Combien de personnes dans le monde n''ont pas accès à une source d''eau potable sûre ?', 'C6'),
('Q148','Quel est le facteur qui affecte le plus la disponibilité de l''eau douce dans le monde ?', 'C6'),
('Q149','Où tombe le plus de pluie dans le monde ?', 'C6'),
('Q150','Quelle est la couleur la plus courante d''un iceberg ?', 'C6'),

('Q151','Qu''est-ce que les ressources naturelles ?', 'C7'),
('Q152','Les ressources naturelles peuvent être renouvelables ou non renouvelables, laquelle est considérée comme une ressource non renouvelable ?', 'C7'),
('Q153','Quelle est la ressource la plus importante pour la vie sur Terre ?', 'C7'),
('Q154','Quelle est la principale source d''énergie renouvelable utilisée dans le monde ?', 'C7'),
('Q155','Quel est le minéral le plus abondant sur Terre ?', 'C7'),
('Q156','Quel est le principal gaz à effet de serre responsable du réchauffement climatique ?', 'C7'),
('Q157','Quel est le minéral le plus précieux sur Terre ?', 'C7'),
('Q158','Quelle est la principale source d''énergie renouvelable dans le monde?', 'C7'),
('Q159','Quelle est la principale utilisation de l''énergie éolienne?', 'C7'),
('Q160','Lequel de ces produits est produit à partir d''une source renouvelable?', 'C7'),
('Q161','Quelle est la source d''énergie la plus utilisée en Europe?', 'C7'),
('Q162','Quel est le nom de la technologie qui utilise la chaleur du soleil pour produire de l''électricité?', 'C7'),
('Q163','Quel est l''avantage des sources d''énergie renouvelables par rapport aux sources d''énergie non renouvelables?', 'C7'),
('Q164','Quel est le plus grand producteur d''énergie solaire au monde?', 'C7'),
('Q165','Quelle est la principale utilisation des ressources minérales?', 'C7'),
('Q166','D''où provient le pétrole ?', 'C7'),
('Q167','Le pétrole brut est souvent raffiné pour produire :', 'C7'),
('Q168','Comment le gaz naturel est-il formé ?', 'C7'),
('Q169','Où sont les plus grandes réserves de gaz naturel dans le monde ?', 'C7'),
('Q170','Quelle est la durée de vie moyenne des panneaux solaires?', 'C7'),
('Q171','Comment le charbon est-il extrait de la terre?', 'C7'),
('Q172','Comment fonctionne l''énergie géothermique?', 'C7'),
('Q173','Où se trouvent les centrales géothermiques?', 'C7'),
('Q174','Quel pays est le plus grand producteur de pétrole au monde?', 'C7'),
('Q175','Quel métal est utilisé dans la production de cellules photovoltaïques pour les panneaux solaires ?', 'C7'),

('Q176','Quelle est la principale cause d''une éruption volcanique ?', 'C8'),
('Q177','Quel est le plus grand volcan actif du monde ?', 'C8'),
('Q178','Quel est le terme utilisé pour décrire le point de la surface de la Terre situé directement au-dessus du foyer d''un tremblement de terre ?', 'C8'),
('Q179','Quel est le terme utilisé pour décrire la mesure de la magnitude d''un tremblement de terre ?', 'C8'),
('Q180','Quel est le terme utilisé pour décrire le processus par lequel les plaques tectoniques de la Terre se déplacent et interagissent, provoquant des tremblements de terre et la création de montagnes et de fosses océaniques ?', 'C8'),
('Q181','Lequel de ces pays a un risque plus élevé de tremblements de terre?', 'C8'),
('Q182','Quel autre événement peut être déclenché par un tremblement de terre?', 'C8'),
('Q183','Quelle est la principale cause des tsunamis ?', 'C8'),
('Q184','Jusqu''où les tsunamis peuvent-ils aller à l''intérieur des terres ?', 'C8'),
('Q185','Quel océan est le plus sujet aux tsunamis ?', 'C8'),
('Q186','Quel est le terme utilisé pour décrire une zone avec peu ou pas de précipitations ?', 'C8'),
('Q187','Quelle est la principale cause de sécheresse dans les régions désertiques ?', 'C8'),
('Q188','Laquelle des régions suivantes est considérée comme l''un des endroits les plus secs de la planète ?', 'C8'),
('Q189','Qu''est-ce qu''un tsunami ?', 'C8'),
('Q190','Qu''est-ce qu''est la canicule ?', 'C8'),
('Q191','Quelle est la catastrophe naturelle la plus fréquente aux États-Unis ?', 'C8'),
('Q192','Quelle est la principale cause d''une tornade ?', 'C8'),
('Q193','Lequel des éléments suivants est un signe d''alerte indiquant qu''un volcan pourrait entrer en éruption prochainement ?', 'C8'),
('Q194','Quelle est la cause la plus fréquente des incendies de forêt ?', 'C8'),
('Q195','Quelle est la différence entre un ouragan et un typhon ?', 'C8'),
('Q196','Quel est le type d''éruption volcanique le plus courant ?', 'C8'),
('Q197','Lequel des éléments suivants est un signe avant-coureur de la formation d''une tornade ?', 'C8'),
('Q198','Quel est le terme utilisé pour désigner une zone sèche et aride qui reçoit moins de 10 pouces de pluie par an ?', 'C8'),
('Q199','Quel est le nom d''une colonne d''air en rotation qui est en contact avec le sol et qui est capable de causer des dommages importants ?', 'C8'),
('Q200','Quel type de catastrophe naturelle s''est produit en 79 après J.-C., ensevelissant les villes de Pompéi et Herculanum sous des cendres et des roches volcaniques ?', 'C8');